### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by AHBruns** [russellsteadman/affiliate#11]
First off, thank you for building Affiliate. It's got a pretty ergonomic API and does exactly what it says on the box.

Now, I use Affiliate on a few websites for clients of my [side hustle](https://authorizewebsites.com/). The sites use a pretty common stack: Next.js (React.js) w/ TypeScript & a headless CMS of some sort. Because I use TS, I try to keep all my dependencies typed if I can. One of the few dependencies that I currently make an exception for is Affiliate because it's basically the only game in town.

So, the reason for this issue is to let you know I'd really appreciate Typescript support. If it's a non-starter I totally get it, but I figured it'd be worthwhile to show support for adding it just in-case you were on the fence about it.

**Comment by teamtofu** [comment]
Hi Alex!

Typescript is already in the works for Affiliate 4. I have been switching to Typescript for my projects as well. Currently Affiliate 4 is not stable (pending testing and some modifications), but I will ping you when it is because putting _any_ everywhere is definitely annoying.

**Comment by AHBruns** [comment]
This is great to hear, and thank you for the quick reply. Looking forward to v4!
