### ISSUE TITLE
affiliate.js - which affiliate programs do you support?

### ISSUE THREAD

**Issue by amwohl** [russellsteadman/affiliate#24]
Can I add affiliate tags to anything other than Amazon? Can I add tags to eBay, Walmart, Alibaba?
Also, do you support tracking IDs for Amazon?

**Comment by russellsteadman** [comment]
Hi @amwohl!

- Affiliate.js is platform agnostic. It isn't built to "support" vendors (e.g. Amazon or eBay), rather it is built to support dynamic URL transformations (e.g. `website.com/product` -> `website.com/product?tag=my-tag`).
- Certain "tracking" identifiers require server-side generation. Affiliate.js is a client-side tool for performing changes to anchor links dynamically (i.e. `<a href="...">...</a>`). If these "tracking" identifiers require server-side generation, you would need to create a server-side script for doing so. Regardless, Affiliate.js would still be able to transform the URLs to add in those identifiers using the [modify function](https://affiliate.js.org/#configtagsmodify).

Did this answer your questions?

**Comment by russellsteadman** [comment]
Question closed. Please create a new issue for further questions and reference [issue #24](https://github.com/russellsteadman/affiliate/issues/24).
