### ISSUE TITLE
How to use programmatically?

### ISSUE THREAD

**Issue by elvismdev** [russellsteadman/affiliate#31]
Let's say I have a simple form with an input field where I would insert an Amazon product URL `https://www.amazon.com/dp/B01MRZFBBH`

On form submit, I would like this Amazon product URL to turn into `https://www.amazon.com/dp/B01MRZFBBH?tag=us-tag` and display below the form to the end user to copy. 

How can I accomplish that with this library?

**Comment by russellsteadman** [comment]
Hi Elvis! The way `affiliate` is currently configured, it cannot be used to directly update the link on form submit. Instead, it would update an anchor link (i.e. `<a href="...">...</a>`). See the documentation for [an example of this](https://affiliate.js.org/#example).

There should be a text-based link affiliation method such as `instance.convertLink('...')`, and I will add that in version `5.0.0` when released.

**Comment by elvismdev** [comment]
@russellsteadman That'd be great! An `instance.convertLink('...')` method would be a great addition to this library.

In the meanwhile I'll see what I can do playing with the current implementation. Maybe I can print the `<a>` tag and then right after update or manipulate the DOM.

**Comment by russellsteadman** [comment]
@elvismdev This will be implemented as `aff.convert('https://www.example.com/')` in the next major release. I plan to push out a major release within the next week.

**Comment by elvismdev** [comment]
@russellsteadman This looks great! I'll look forward to the next release, thank you!
