### ISSUE TITLE
Decouple affiliate utilities from DOM functionality

### ISSUE THREAD

**Issue by RodrigoTomeES** [russellsteadman/affiliate#36]
Hi,

I'm very interested in the library but I think it would be better to separate the affiliate utilities from the DOM related functionality. This way could be used for more projects, for example, creating the affiliates in a backend with Node where the DOM functionality is not needed. Also, both packages could be maintained independently.

I've been doing tests and got it to work without the DOM functionality using the 'convert' function but still this code is loaded in the application.

```js
const aff = window.Affiliate.create({
  tags: [
    {
      hosts: ['amazon.es', 'www.amazon.es'],
      query: {
        tag: 'my-super-affiliate', // This means ?ref=my-tag
      },
    },
  ],
});

console.log(aff.convert('https://www.amazon.es/LEGO-10212-Star-Lanzadera-imperial/dp/B0041I0N9A/?_encoding=UTF8&pd_rd_w=Mqdi6&content-id=amzn1.sym.dfbf490a-d858-4445-bf49-2916dec94084&pf_rd_p=dfbf490a-d858-4445-bf49-2916dec94084&pf_rd_r=XAQC9NM704AV77FZ278M&pd_rd_wg=rmQ9K&pd_rd_r=e03e1afd-e5f6-426d-90ef-602a0a48d39b&ref_=pd_gw_ci_mcx_mr_hp_atf_m&tag=test')); // convert a provided URL or string
console.log(aff.convert('https://www.amazon.es/dp/B0041I0N9A')); // convert a provided URL or string

// Output
"https://www.amazon.es/LEGO-10212-Star-Lanzadera-imperial/dp/B0041I0N9A/?_encoding=UTF8&amp;pd_rd_w=Mqdi6&amp;content-id=amzn1.sym.dfbf490a-d858-4445-bf49-2916dec94084&amp;pf_rd_p=dfbf490a-d858-4445-bf49-2916dec94084&amp;pf_rd_r=XAQC9NM704AV77FZ278M&amp;pd_rd_wg=rmQ9K&amp;pd_rd_r=e03e1afd-e5f6-426d-90ef-602a0a48d39b&amp;ref_=pd_gw_ci_mcx_mr_hp_atf_m&amp;tag=my-super-affiliate"
"https://www.amazon.es/dp/B0041I0N9A?tag=my-super-affiliate"
```

What do you think of my proposal?

Thank you very much for the work, and I am willing to collaborate in the project if you need my help or I see something to improve 🚀

**Comment by russellsteadman** [comment]
Hi @RodrigoTomeES ,

My main concern with separating the conversion logic is that the complexity of the library is mainly in its interaction with `MutationObserver` for the DOM. This library is intended to help with *dynamic* conversion in web environments. The *static* conversion you are showing could be accomplished in fewer lines of code with no imported libraries.

```js
// Affiliate is not imported

const convert = (link) => {
    const url = new URL(link);
    if (['amazon.es', 'www.amazon.es'].includes(url.hostname)) {
        url.searchParams.set('tag', 'my-super-affiliate');
    }
    return url.href;
};

convert('https://www.amazon.es/LEGO-10212-Star-Lanzadera-imperial/dp/B0041I0N9A/?_encoding=UTF8&pd_rd_w=Mqdi6&content-id=amzn1.sym.dfbf490a-d858-4445-bf49-2916dec94084&pf_rd_p=dfbf490a-d858-4445-bf49-2916dec94084&pf_rd_r=XAQC9NM704AV77FZ278M&pd_rd_wg=rmQ9K&pd_rd_r=e03e1afd-e5f6-426d-90ef-602a0a48d39b&ref_=pd_gw_ci_mcx_mr_hp_atf_m&tag=test');
// Yields https://www.amazon.es/LEGO-10212-Star-Lanzadera-imperial/dp/B0041I0N9A/?_encoding=UTF8&pd_rd_w=Mqdi6&content-id=amzn1.sym.dfbf490a-d858-4445-bf49-2916dec94084&pf_rd_p=dfbf490a-d858-4445-bf49-2916dec94084&pf_rd_r=XAQC9NM704AV77FZ278M&pd_rd_wg=rmQ9K&pd_rd_r=e03e1afd-e5f6-426d-90ef-602a0a48d39b&ref_=pd_gw_ci_mcx_mr_hp_atf_m&tag=my-super-affiliate

convert('https://www.amazon.es/dp/B0041I0N9A')
// Yields https://www.amazon.es/dp/B0041I0N9A?tag=my-super-affiliate
```

I think that in those cases `affiliate` is simply not necessary. Not everyone is familiar with the `URL` object, so abstraction may still be helpful. Let me know what you think.

-- Russell

**Comment by RodrigoTomeES** [comment]
Hi @russellsteadman,

Very interesting the use of URL to this purpose I didn't know it, that should be sufficient,

Thanks so much!! 👌

**Comment by russellsteadman** [comment]
Perfect. `URL` is a global for Node.js, so you don't need to import anything.
