### ISSUE TITLE
[new feature] change shorten amazon links posted by users by my own links

### ISSUE THREAD

**Issue by pioc92** [russellsteadman/affiliate#38]
Hi, thanks for your script.
Is-it possible to make a plugin or function to convert shorten amazon links (ex: https://amzn.to/3EYDIZO) to real amazon.fr link with my tag? Because i have a forum and people post amzn.to links to bypass affiliate-js
Thanks!

**Comment by russellsteadman** [comment]
Hi @pioc92 

The problem with unshortening `amzn.to` links is that it cannot be done client-side. Amazon does not provide CORS for `amzn.to`, so the client is unable to resolve the url. You will have to make changes on the backend to resolve these links.

Example:
```js
fetch('https://amzn.to/3EYDIZO');
// This fails due to CORS
```

**Comment by pioc92** [comment]
ok i will do it server-side with php thanks!
